// Generated from auth_config.yaml by scripts/generate-auth-config.js
// Do not edit this file directly.

export const authConfig = {
  "auth": {
    "enabled": true,
    "secrets": {
      "default": "SECRET"
    },
    "rules": [
      {
        "pathPrefix": "/",
        "secretName": "default"
      }
    ]
  }
};
